version: '3'

services:
    web:
        image: nginx:stable-alpine
        container_name: web
        volumes:
            - "./web/www:/usr/share/nginx/html:ro"
            - "./web/nginx.conf:/etc/nginx/nginx.conf:ro"
        ports:
            - "127.0.0.1:80:80"